online_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_chat.urls', namespace='chat')),
]

test_chat/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from test_chat.views import *

app_name = "chat"

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='auth.html'), name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='auth.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('rooms/', rooms, name='rooms'),
    path('chat/<slug:slug>', chat, name='chat'),
    path('chat/', chat, name='chat'),
]

test_chat/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth import get_user_model

User = get_user_model()


class Room(models.Model):
	name = models.CharField(max_length=255, unique=True, verbose_name="Чат")
	slug = AutoSlugField(populate_from='name', unique=True, null=False, editable=False)
	creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="chat_creator", verbose_name="Создатель")
	created = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")

	def __str__(self):
		return f'{self.name}'


class Message(models.Model):
	room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="message", verbose_name="Сообщение")
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user", verbose_name="Отправитель")
	text = models.TextField()
	created = models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")

	class Meta:
		ordering = ('created',)

test_chat/forms.py
from django import forms
from test_chat.models import *

class AddChatsForms(forms.ModelForm):
    class Meta:
        model = Room
        fields = ('name',)

test_chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from test_chat.models import *
from test_chat.forms import *

@login_required
def rooms(request):
	rooms = Room.objects.all()
	form = AddChatsForms()
	return render(request, 'rooms.html', locals())

@login_required
def chat(request, slug=None):

	if slug:
		room = get_object_or_404(Room, slug=slug)
	else:
		if request.method == 'POST':
			form = AddChatsForms(request.POST)
			if form.is_valid():
				cd = form.cleaned_data
				name = cd['name']
				user = request.user
				room = Room.objects.create(name=name, creator=user)
			else:
				messages.error(request, "This chat already exists.")
				return redirect('chat:rooms')
		else:
			return redirect('chat:rooms')
	all_messages = Message.objects.filter(room=room).all()
	count = room.message.values('user').distinct().count()
	return render(request, 'chat.html', locals())

templates/auth.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Авторизация</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	<div class="blur"></div>
	<div class="auth container">
		<div class="auth-container">
			<div>
				<h1 class="auth-title">Авторизация</h1>
				<form method="post" class="auth-form">
					{%csrf_token%}
					<div class="form-input">
						<input type="text" name="username" placeholder="Логин">
					</div>
					<div class="form-input">
						<input type="password" name="password" placeholder="Пароль">
					</div>
				  	<button type="submit" class="btn">Войти</button>
				</form>
			</div>
		</div>	
	</div>

	

</body>
</html>

templates/chat.html
{% load static %}
{% load chat_tags %}
<!DOCTYPE html>
<html>

<head>
	<title>Авторизация</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>
	{% if messages %}
		{% for message in messages %}
			<script type="text/javascript">
				alert({{message}});
				{% comment %} alert('The message was empty!!!'); {% endcomment %}
			</script>
		{% endfor %}
	{% endif %}
	<div class="chat room container">
		<div class="auth-container">
			<div class="">
				<h1 class="auth-title">
					{{room}}
					<p class="date">{{count}} участника</p>
					<a href="{% url 'chat:rooms' %}" class="door"><img src="{% static 'img/door.svg' %}"></a>
				</h1>

				<div class="chat-body" id="chat-body">
				{% for message in all_messages %}
					{% room_date message.pk message.room %}
					
					{% if message.user == request.user %}
						<div class="chat-all">
							<div class="chat-response {% user_msg message.pk message.room message.user %}">
								<p>{{message.text}}</p>
								<p class="time">
									{{message.created|date:"H:i"}}
									<img src="{% static 'img/read.svg' %}">
								</p>
								<div class="chat-reactangle"></div>
							</div>
						</div>
					{% else %}
						<div class="chat-all left-container">
							<div class="chat-response left {% user_msg message.pk message.room message.user %}">
								<h5> {% firstof message.user.get_full_name message.user %}</h5>
								<p>{{message.text}}</p>
								<p class="time">{{message.created|date:"H:i"}}</p>
								<div class="chat-reactangle"></div>
							</div>
						</div>
					{% endif %}
				{% endfor %}
				</div>
				<form action"." method="post" class="auth-form"> {%csrf_token%}
					<div class="form-input">
						<input type="text" id="chat-message-input" name="message" placeholder="Сообщение...">
						<button id="chat-message-submit" class="btn"><img src="{% static 'img/send.svg' %}"></button>
					</div>
				</form>
			</div>
		</div>
	</div>
	{{room.slug|json_script:"json-roomname"}}
	{{request.user.get_full_name|json_script:"json-full_name" }}
	{{request.user.username|json_script:"json-username"}}
	<script>
		const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
		const userName = JSON.parse(document.getElementById('json-username').textContent);
		const full_name = JSON.parse(document.getElementById('json-full_name').textContent);

		const chatSocket = new WebSocket(
			'ws://'	+ window.location.host + '/ws/' + roomName + '/'
		);
		chatSocket.onmessage = function(e) {
			const data = JSON.parse(e.data);

			if (data.message) {
				let h = new Date().getHours();
				let m = new Date().getMinutes();
				if(full_name != ''){name=full_name}else{name=userName}

				let html = ""
				if (data.username == userName) {
					html += '<div class="chat-all"><div class="chat-response index">'
					html += '<p>' + data.message + '</p><p class="time">'
					html += h + ':' + m + '<img src={% static "img/check.svg" %}></p><div class="chat-reactangle"></div></div></div>'
				}
				else{
					html += '<div class="chat-all left-container"><div class="chat-response left index">'
					html += '<h5>' + data.username + '</h5>'
					html += '<p>' + data.message + '</p><p class="time">'
					html += h + ':' + m + '</p><div class="chat-reactangle"></div></div></div>'
				}
				document.querySelector('#chat-body').innerHTML += html;
				scrollToBottom();
			} else {
				alert('The message was empty!!!');
			}
		}
		chatSocket.onclose = function(e) {
			console.log('onclose');
		}

		document.querySelector("#chat-message-submit").onkeyup = function(e) {
			if (e.keyCode === 13) {
				document.querySelector("#chat-message-submit").click();
			}
		};

		document.querySelector('#chat-message-submit').onclick = function(e) {
			e.preventDefault();
			const messageInput = document.querySelector('#chat-message-input');
			const message = messageInput.value;
			if (message != ''){
				chatSocket.send(JSON.stringify({
					'message': message,
					'username': userName,
					'room': roomName,
				}));
			}
			messageInput.value = '';
			return false;
		}
		function scrollToBottom(){
			const objDiv = document.querySelector('#chat-body');
			objDiv.scrollTop = objDiv.scrollHeight;
		}
		scrollToBottom();
	</script>
</body>
</html>

templates/rooms.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Авторизация</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	{% if request.user.is_authenticated %}
		<a href="{% url 'chat:logout' %}" class="doorr"><img src="{% static 'img/door.svg' %}"></a>
	{% endif %}
	<div class="room container">
		<div class="auth-container">
			<div class="">
				<h1 class="auth-title">Выберите / создайте чат</h1>
				<form action="{% url 'chat:chat' %}" method="post" class="auth-form">
					{%csrf_token%}
					<div class="all-rooms">
						{% for room in rooms %}
							<a href="{% url 'chat:chat' room.slug %}" class="next-chat">
								<p>{{room}}</p>
								<img src="{% static 'img/next.svg' %}">
							</a>
						{% endfor %}
					</div>
					<div class="form-input">
						<input type="text" name="name" placeholder="Введите название чата" required>
				  		<button type="submit" class="btn">Создать</button>
					</div>
				</form>
			</div>
		</div>	
	</div>
	{% if messages %}
		{% for message in messages %}
			<script type="text/javascript">
				alert("{{message}}");
			</script>
		{% endfor %}
	{% endif %}
</body>
</html>